/**
 * Profile Actions 
 */

const CONTEXT: string = 'ADMIN';

/**
 * ngrx setup start --
 */
interface IAdminActions {
    FEATURE_INIT: string;
    FEATURE_INITIALIZED: string;
    FEATURE_ADD: string;
    FEATURE_EDIT: string;
    FEATURE_GET: string;
    FEATURE_DETAILS_FETCHED: string;
    FEATURE_DELETE: string;
}

export const ADMIN_ACTIONS: IAdminActions = {
    FEATURE_INIT: `${CONTEXT}_FEATURE_INIT`,
    FEATURE_INITIALIZED: `${CONTEXT}_FEATURE_INITIALIZED`,
    FEATURE_ADD: `${CONTEXT}_FEATURE_ADD`,
    FEATURE_EDIT: `${CONTEXT}_FEATURE_EDIT`,
    FEATURE_GET: `${CONTEXT}_FEATURE_GET`,
    FEATURE_DETAILS_FETCHED: `${CONTEXT}_FEATURE_DETAILS_FETCHED`,
    FEATURE_DELETE: `${CONTEXT}_FEATURE_DELETE`,
};
