/**
 * Profile Actions 
 */

const CONTEXT: string = 'PROFILE';

/**
 * ngrx setup start --
 */
interface IProfileActions {
    INIT: string;
    DETAILS: string;
    DETAILS_FETCHED: string;

    //Achievement
    INITIALIZE_GET_ACHIEVEMENTS: string;
    GET_ACHIEVEMENTS: string;
    INITIALIZE_ADD_ACHIEVEMENT: string;
    ADD_ACHIEVEMENT: string;

    INITIALIZE_GET_CERTIFICATES: string;
    GET_CERTIFICATES: string;

    INITIALIZE_GET_SKILLS: string;
    GET_SKILLS: string;

    INITIALIZE_GET_EDUCATION:string;
    GET_EDUCATION: string;

    INITIALIZE_GET_EMPLOYMENT_HISTORY: string;
    GET_EMPLOYMENT_HISTORY: string;

    INITIALIZE_GET_EXPERIENCE: string;
    GET_EXPERIENCE: string;
}

export const PROFILE_ACTIONS: IProfileActions = {
    INIT: `${CONTEXT}_INIT`,
    DETAILS: `${CONTEXT}_DELAILS`,
    DETAILS_FETCHED: `${CONTEXT}_DELAILS_FETCHED`,

    //Achievement
    INITIALIZE_GET_ACHIEVEMENTS: `${CONTEXT}_INITIALIZE_GET_ACHIEVEMENTS`,
    GET_ACHIEVEMENTS: `${CONTEXT}_GET_ACHIEVEMENTS`,
    INITIALIZE_ADD_ACHIEVEMENT: `${CONTEXT}_INITIALIZE_ADD_ACHIEVEMENT`,
    ADD_ACHIEVEMENT: `${CONTEXT}_ADD_ACHIEVEMENT`,

    //Ceritificates
    INITIALIZE_GET_CERTIFICATES: `${CONTEXT}_INITIALIZE_GET_CERTIFICATES`,
    GET_CERTIFICATES: `${CONTEXT}_GET_CERTIFICATES`,

    //Skills
    INITIALIZE_GET_SKILLS: `${CONTEXT}_INITIALIZE_GET_SKILLS`,
    GET_SKILLS: `${CONTEXT}_GET_SKILLS`,

    //Education
    INITIALIZE_GET_EDUCATION: `${CONTEXT}_INITIALIZE_GET_EDUCATION`,
    GET_EDUCATION: `${CONTEXT}_GET_EDUCATION`,

    //Employment History
    INITIALIZE_GET_EMPLOYMENT_HISTORY: `${CONTEXT}_INITIALIZE_GET_EMPLOYMENT_HISTORY`,
    GET_EMPLOYMENT_HISTORY: `${CONTEXT}_GET_EMPLOYMENT_HISTORY`,

    //Experience
    INITIALIZE_GET_EXPERIENCE: `${CONTEXT}_INITIALIZE_GET_EXPERIENCE`,
    GET_EXPERIENCE: `${CONTEXT}_GET_EXPERIENCE`,
};
